name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run tests
      run: |
        javac *.java
        java -DEXT_MIN=$EXPECTED_MIN -DEXT_MAX=$EXPECTED_MAX -DEXT_SUM=$EXPECTED_SUM -DEXT_MULT=$EXPECTED_MULT Test
      env:
        EXPECTED_MIN: 2
        EXPECTED_MAX: 7
        EXPECTED_SUM: 16
        EXPECTED_MULT: 168

    - name: Notify on success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: 675829379
        token: 6586894380:AAHTL-SSy8QkJ_HZnwAtFvWFHuDBaiaS6zw
        message: "Tests passed successfully! 🎉"

    - name: Notify on failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: 675829379
        token: 6586894380:AAHTL-SSy8QkJ_HZnwAtFvWFHuDBaiaS6zw
        message: "Tests failed! ❌"
